---
- name: Configuracion Inicial del Proyecto
  hosts: routers
  gather_facts: false
  
  tasks:
    - name: Configurar el Mensaje del Dia (Banner MOTD)
      cisco.ios.ios_banner:
        banner:  motd
        text: |
          ***************************************		
          * ACCESO RESTRINGIDO - PROYECTO REDES *
          *****************************************
        state: present

    - name: Guardar la configuracion en los equipos (write memory)
      cisco.ios.ios_config:
        save_when: modified
